[tool.black]
line-length = 88
target-version = ['py37']
exclude = 'doku/static/'

[tool.pylint.master]
ignore = 'doku/static/'
[tool.pylint.messages_control]
disable = "C0330, C0326"
[tool.pylint.format]
max-line-length = "88"

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88
py_version = '37'
only_sections = true
skip = 'doku/static/,doku/__init__.py'
