"""resource

Revision ID: 78714585da66
Revises: 533bb8c681be
Create Date: 2020-05-22 01:05:02.754412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78714585da66'
down_revision = '533bb8c681be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doku_resource',
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doku_resource')
    # ### end Alembic commands ###
