"""empty message

Revision ID: b6f593818541
Revises: c2d7aa36d0e7
Create Date: 2022-06-17 18:35:58.043728

"""
from alembic import op
import sqlalchemy as sa
from doku.models import TSVector


# revision identifiers, used by Alembic.

revision = 'b6f593818541'
down_revision = 'c2d7aa36d0e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doku_document', sa.Column('__ts_vector__', TSVector(), sa.Computed("to_tsvector('english', name)", persisted=True), nullable=True))
    op.create_index('doku_document___ts_vector__', 'doku_document', ['__ts_vector__'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('doku_document___ts_vector__', table_name='doku_document', postgresql_using='gin')
    op.drop_column('doku_document', '__ts_vector__')
    # ### end Alembic commands ###
