"""user_name

Revision ID: b86f36e8e5f1
Revises: 78714585da66
Create Date: 2020-07-05 16:08:01.318866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b86f36e8e5f1'
down_revision = '78714585da66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doku_user', sa.Column('name', sa.String(length=48), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doku_user', 'name')
    # ### end Alembic commands ###
