"""remove_base_style

Revision ID: c2d7aa36d0e7
Revises: 0bb1ccf2f77f
Create Date: 2020-11-27 19:35:28.962986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2d7aa36d0e7'
down_revision = '0bb1ccf2f77f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('doku_template_base_style_id_fkey', 'doku_template', type_='foreignkey')
    op.drop_column('doku_template', 'base_style_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doku_template', sa.Column('base_style_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('doku_template_base_style_id_fkey', 'doku_template', 'doku_stylesheet', ['base_style_id'], ['id'])
    # ### end Alembic commands ###
