"""Snippets

Revision ID: e81e50a2960c
Revises: 3040ce8bd808
Create Date: 2020-08-30 20:43:31.245490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e81e50a2960c'
down_revision = '3040ce8bd808'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doku_snippet',
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('use_markdown', sa.Boolean(), nullable=True),
    sa.Column('css_class', sa.String(length=255), nullable=True),
    sa.Column('content', sa.UnicodeText(), nullable=False),
    sa.Column('compiled_content', sa.UnicodeText(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.add_column('doku_variable', sa.Column('snippet_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'doku_variable', 'doku_snippet', ['snippet_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'doku_variable', type_='foreignkey')
    op.drop_column('doku_variable', 'snippet_id')
    op.drop_table('doku_snippet')
    # ### end Alembic commands ###
