name: unittest

on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
     
      - name: Setup Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: '3.x'
      
      - name: Install Python Requirements
        run: pip install -r requirements.txt

      - name: Start Database
        run: cd docker && docker-compose up -d

      - name: Launch Tests
        run: |
          pytest doku/tests --junitxml=TESTS.xml
          junit 'TESTS.xml'
        env:
          REDIS_HOST: 'redis'