name: upload

on:
  push:
    branches: [ main ]

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Registry
        uses: docker/login-action@v1 
        with:
          registry: reg.desk-lab.de
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD}}

      - name: Build and push doku-static
        uses: docker/build-push-action@v2
        with:
          file: 'doku/static/Dockerfile'
          context: 'doku/static'
          push: true
          tags: |
            reg.desk-lab.de/doku-static:${{ github.sha }}
            reg.desk-lab.de/doku-static

      - name: Build and push doku
        uses: docker/build-push-action@v2
        with:
          file: './Dockerfile'
          context: '.'
          push: true
          tags: |
            reg.desk-lab.de/doku:${{ github.sha }}
            reg.desk-lab.de/doku
