name: Build and Deploy

on:
  workflow_run:
    workflows: ["Test"]
    branches: [main]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Registry
        uses: docker/login-action@v1 
        with:
          registry: reg.desk-lab.de
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD}}

      - name: Build and push doku-static
        uses: docker/build-push-action@v2
        with:
          file: 'doku/static/Dockerfile'
          context: 'doku/static'
          push: true
          tags: |
            reg.desk-lab.de/doku-static:${{ github.sha }}
            reg.desk-lab.de/doku-static

      - name: Build and push doku
        uses: docker/build-push-action@v2
        with:
          file: './Dockerfile'
          context: '.'
          push: true
          tags: |
            reg.desk-lab.de/doku:${{ github.sha }}
            reg.desk-lab.de/doku
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Run Ansible Playbook
        working-directory: './.github/ansible'
        env:
          REMOTE_PROJECT_SRC: ${{ secrets.DEPLOY_PROJECT_SRC }}
          ANSIBLE_REMOTE_USER: ${{ secrets.DEPLOY_USER }}
          SSH_PRIVATE_KEY : ${{ secrets.DEPLOY_SSH_KEY }}
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          ANSIBLE_HOST_KEY_CHECKING: 'False'
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "$SSH_PRIVATE_KEY"
          ansible-playbook --inventory ${{ secrets.DEPLOY_HOST }}, deploy.yml
